project:
  type: website

website:
  title: "Zijia Zhang"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: 
    - litera
    - brand
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto

